import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/web/navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";

// 👇 引入你的 Convex Provider（请根据你的实际路径修改）
import {ConvexClientProvider} from "./ConvexClientProvider"; 
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* 👇 1. 用 Convex Provider 包裹最外层，提供全局身份验证状态 */}
        <ConvexClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            
            {/* 👇 2. 把 Navbar 放进来，通常放在 main 的上方 */}
            <Navbar />

            <main className="max-w-7xl w-full mx-auto px-4 md:px-6 lg:px-8 flex-1">
              {children}
            </main>
            <Toaster />
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}